### ISSUE TITLE
Custom values?

### ISSUE THREAD

**Issue by dragonfire1119** [mostafaznv/laracache#7]
How would you use the cache with custom values in a where clause, for example?

```
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Mostafaznv\LaraCache\Traits\LaraCache;

class Article extends Model
{
    use LaraCache;
    
    /**
     * Define Cache Entities Entities
     *
     * @return CacheEntity[]
     */
    public static function cacheEntities(): array
    {
        return [
            CacheEntity::make('latest')
                ->validForRestOfDay()
                ->cache(function() {
                    return Article::query()->latest()->where('status', '[custom-status-here?]')->first();
                })
        ];
    }
}
```

**Comment by mostafaznv** [comment]
Hi @dragonfire1119 

In most cases, cache queries are static. If you have to pass a dynamic value to a query, maybe you shouldn't cache it at all.

But anyway, this package doesn't create cache entities manually. it will generate/regenerate them during model events (created, updated, deleted and restored). so you can't pass custom values to it.


But,
Based on your sample code, I will create separate entities for each status. One for articles with published status, and another for articles with draft status. so I don't need a custom value anymore.

**Comment by dragonfire1119** [comment]
@mostafaznv Thank you for your response. However, I believe that caching dynamic queries is beneficial because they typically take the longest to query, particularly when dealing with relationships.
