### ISSUE TITLE
How often does this refresh the cache?

### ISSUE THREAD

**Issue by vins13pattar** [mostafaznv/laracache#8]
It is firing "Mostafaznv\LaraCache\Jobs\RefreshCache" event twice every second!!! My CPU usage is going high. Also, I used caching on only one model. Is it normal? 

<img width="799" alt="image" src="https://user-images.githubusercontent.com/333259/178744901-17cbb537-696e-4403-a1f0-1204a45546c1.png">

**Comment by mostafaznv** [comment]
Hi @vins13pattar 

Not, it's not normal.
Can you explain how you are using it?

This event dispatches whenever you perform create/update/delete on records of your model

**Comment by vins13pattar** [comment]
@mostafaznv 
 
Model

```php
public static function cacheEntities(): array
{
    return [
        CacheEntity::make('all.active')
            ->forever()
            ->cache(function () {
                return Corporate::query()->where('is_active', true)->latest()->get();
        }),
    ];
}
```

Query in controller,
```
Corporate::cache()->get('all.active')
````

When the query is hit the queue worker keeps processing all the events mentioned above. There are no other queries running on the mentioned model.

**Comment by mostafaznv** [comment]
Allright.
Can you tell me if you are calling `refresh` method manually?

```php
// example
TestModel::cache()->refresh(CacheEvent::CREATED());
```


Or are you trying to dispatch `RefreshCache` manually?

----

I think there is a kind of loop in your project and it is cause of this abnormal activity.

As you can see, this is my own terminal and `RefreshCache` works normally:

![Screen Shot 1401-04-24 at 2 41 31 PM](https://user-images.githubusercontent.com/7619687/179203063-a45a2910-208b-4b60-b111-f917f4b1a6f8.png)

**Comment by vins13pattar** [comment]
I destroyed containers and rebuilt them. Did ran `artisan optimize` and it started working normally...! No code is changed. Strange!! Thank you for the response and helping me out @mostafaznv
